version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_DSN: host=db user=postgres password=postgres dbname=movies port=5432 sslmode=disable
      JWT_SECRET: your_jwt_secret
      PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env

volumes:
  db_data:
